name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Gradle 래퍼에 실행 권한 설정
      run: chmod +x ./gradlew

    - name: JDK 17 설정
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Gradle로 빌드
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: clean bootJar

    - name: 도커 이미지 빌드
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nonabang .

    - name: 도커 로그인
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: 도커 허브에 푸시
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/nonabang

  run-docker-image-on-ec2:
    needs: build-docker-image
    runs-on: self-hosted

    steps:

      - name: docker pull
        run: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/nonabang

      - name: docker stop container
        run: sudo docker stop $(sudo docker ps -q) 2>/dev/null || true

      - name: docker run new container
        run: sudo docker run --name github-actions-test --rm -d -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/nonabang

      - name: delete old docker image
        run: sudo docker system prune -f
